### ISSUE TITLE
В тз, нет про Clock

### ISSUE THREAD

**Issue by MisterZurg** [blackav/smart-home-binary#1]
Пример теста: Clock, IAMHERE (6, 2): Dgb_fxUGAgdDTE9DSzAxsw
Сервер ожидает результат, не указанный в условии:
```
ServerWant : [14 6 255 127 21 6 1 7 67 76 79 67 75 48 49 28]
Processed: [14 6 255 127 21 6 1 28]
```

**Comment by blackav** [comment]
это соответствует спецификации
